# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jonathan Thomas
tagline:          ''
description:      'Engineer.'
baseurl:          /
url:              https://jonathoma.github.io/
plugins:          [jekyll-paginate, jekyll-seo-tag]
author:
  name:           Jonathan Thomas
paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jonathoma

twitter:          https://twitter.com/jonathoma
twitter:username: jonathoma
twitter:creator:  jonathoma

linkedin:         https://www.linkedin.com/in/jonathoma/
