# Permalinks
permalink:           pretty

# Setup
title:               Jonathan Thomas
tagline:             Computer Science / Mathematics / Philosophy
url:                 http://jonathoma.github.io/
paginate:            1
baseurl:             /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jonathan Thomas
  url:               https://twitter.com/jonathoma
  email:             jonthoma@umich.edu

# Custom vars
version:             1.0.0
github:              jonathoma
repo:                https://github.com/jonathoma/

pages_list:       
  About: '/about'
  Projects: '/projects'
  GitHub : 'https://github.com/jonathoma'
  Resume: '/resume'
