# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jonathan Thomas
tagline:          'Computer Science / Math / Philosophy'
description:      'Current computer science and mathematics student at the University of Michigan - Ann Arbor.'
url:              http://jonathoma.github.io
baseurl:          /
plugins:          [jekyll-paginate]
author:
  name:           'Jonathan Thomas'
paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jonathoma

twitter:          https://twitter.com/jonathoma

linkedin:         https://www.linkedin.com/in/jonathoma/
